### ISSUE TITLE
f

### ISSUE THREAD

**Issue by braainsiogame** [dot-eye-oh/modpack#1]
Dark clouds hung overhead as raindrops pelted windows in a rhythmic pit-pat fashion across a sleepy town in the suburbs. The melody prompted the frogs outside to sing their croaky song, while the flowers swayed to the beat. All the while, inside a large home, was a young boy who sat on a stool, gazing at the yard outside. His legs swished back and forth in tune with the grandfather clock as he watched the droplets drip down the window.

Sunny was bored, it was a Friday afternoon and he had nothing to do. His friends were going to come over tomorrow for their weekly Saturday cartoons and the anticipation made the rainy day all the more boring. His older sister, Mari, wasn’t even around to distract him from his boredom as she was out of the house. She was out for another one of her college prep classes, and Sunny could only grimace as he remembered there were only two years left before she left for college. It wouldn’t be for another hour or so until she came back.

Sunny put his feet on the stool and put his face in his knees to try and get those bothersome thoughts out of his head, but suddenly, he heard a splish and a splash as he watched someone in a pink umbrella walk across the sidewalk. He recognized that umbrella, after all, he saw that umbrella every single rainy day at school.

Indeed, he saw Aubrey carry an umbrella as she walked through the rain, although, the umbrella wasn’t being used in the way it was meant to be used. She walked along with the umbrella slung across her shoulder, while the rain drenched her. Every few steps, she made a loud cry as she swung her umbrella like she was going for a home-run. She also stomped in every puddle on purpose with no exceptions, getting drenching herself in the process.

Sunny jumped from his stool, bursted out the door, and ran outside.

"Hey! Aubrey!” Sunny yelled out,

That seemed to break Aubrey out of her mood as she turned to face Sunny.

“Oh, hi, Sunny,” she watched as Sunny ran out of the house up to her.

“Come here!” He grabbed Aubrey and started pulling her by the arm.

“Huh? W-“ Aubrey tried to say something, but Sunny dragged her into his home before she could utter a sentence.

Sunny stumbled a bit as he rushed them both into his home. Once he got both of them inside, he spoke.

“I’ll get some towels, um, sit there.” Sunny stumbled a bit with his words. He pointed to a spot on the sofa and he scurried away.

Aubrey was confused to say the least, but Sunny was already gone. She put her umbrella on the side of the coat rack and took off her shoes and socks. The sound of footsteps and the clattering of utilities and cabinets sounded out upstairs as she sat on the sofa. Once she sat, a squish echoed and Aubrey grimaced. The couch she was sitting on was definitely expensive. It wouldn’t do to damage something so nice. Instead, Aubrey got up and sat on a spot near the fireplace on the rug. It was very toasty.

A black ball suddenly jumped onto her lap, and Aubrey lit up with glee. Mari recently got a kitten named Mewo, and Mewo walked up to her and nuzzled her head into her stomach. She squealed a bit and excitedly ran her hands through Mewo’s fur, and Mewo gave the cutest purr in response.

Eventually, the rattling upstairs stopped, and Sunny came running down the stairs with a handful of towels, a blanket, a hair drier, and a bunch of stuffed toys.

“Here.” He handed Aubrey a bunch of towels, but they were clumped into an unwieldy ball much like an onion. Aubrey managed to peel away a layer from the towel onion and dried the rain off herself.

Mewo promptly jumped from Aubrey’s lap and tackled the towel onion. She attempted to defeat it but the many layers kept falling on the small kitten.  

Sunny was behind the TV, rustling a pile of wires. He could’ve sworn there was an open outlet behind here, but all he saw was a mess of power strips and dust.

“Found it.” The hair drier in Sunny’s hand came to life and he handed it to Aubrey. A loud noise erupted throughout the room and it drowned out everything else which scared Mewo away. The towel onion laid on the floor, undefeated.

Aubrey didn’t realize just how cold she was and that made the hot air from the drier heavenly. She ran it through her hair a few times and over the parts of her clothes that were the most drenched. After a few rounds, her brain slowly regained its functions and she realized she never thanked Sunny, and hurriedly turned his way.

“Thanks Sunny, but you didn’t have to do all that.” Aubrey said, but Sunny just shook his dusty head.

“You were going to get sick if you didn’t dry off.” Sunny explained.

“It’s not that big a –“ Aubrey tried to say, but Sunny cut her off.

“Remember when I fell in the lake and Mari dove in and helped me? We got really sick after that. Our mom yelled at us for hours. Also, today is Friday, if you get sick, then we won’t be able to hang out tomorrow.” Sunny held out the blanket. After a moment, Aubrey took the blanket and wrapped it around her. She took a seat on the rug next to the fireplace.

“Fine, but wipe yourself off as well Sunny, you’re dusty.” Aubrey peeled off another layer from the towel onion and threw it onto Sunny.

An awkward silence began to pass as the fireplace crackled and they both dusted/dried themselves off. Sunny had a number of questions, ‘why did you go outside in the rain’, ‘is your umbrella broken’,  ‘why were you so angry’, he thought for a while, but asked had to be asked.

“Are you okay?”

Aubrey mumbled a sound like a deflated bike horn.

“That doesn’t sound like okay. Um, want to talk about it?” Sunny sat down on the rug next to Aubrey, he patted the ground and handed her a stuffed toy with bushy eyebrows. “It’ll be like the park, I’ll hear you out.”

Aubrey huffed. She planted her face in her blanket and closed her eyes. After a while, she sighed, and pulled her head up.

Aubrey took a deep breath, “Today was awful! Bun bun made a mess of his room and Dad yelled at me for not cleaning up after her even though I was just about to. My favorite pen also disappeared and I couldn’t even find it after searching for a whole hour!”

“Is that it?” Sunny asked. It sounded bad, but he knew Aubrey well enough that what she just described wasn’t enough to make her that furious to run out in the rain.

Aubrey grimaced, she tried to think of another excuse but sighed, “Mom and Dad are fighting.” She said with a quiet voice.

“They were arguing again and they started screaming at each other. It went on for so long, and I’m not exactly sure what they were arguing about, but I couldn’t think at all. I don’t think they even knew I was there and I was really really scared,” Aubrey took a deep breath, “So… I just grabbed my umbrella and ran out. At first I was kinda sad, but then I got really angry. It’s not fair! Why can’t they just get along!”

Sunny stayed quiet.

Aubrey threw Sunny’s stuffed toy, Brows, to the side as tears formed in her eyes. It bounced harmlessly against the floor. Sunny handed Aubrey another toy, Happy the yellow gumdrop.

“Thanks.” Aubrey plopped down on the rug to stare at the ceiling and sniffled. She put the stuffed toy on her stomach and moped.

“I really want them to make up…”

Sunny had to think. He really didn’t know much about Aubrey’s home, she never did speak about it with any of them before.

“I don’t really know what anyone can do about mom and dad, but I do feel a little better after talking about it,” Aubrey squished Happy and played with it in her hands.

“Well… at least you have us don’t you?” Sunny said, “I know it’s not exactly the same, but Hero always says that it doesn’t matter what comes at us, we’ll be able to get through it, as long as we do it together. Remember you can always rely on us.”

“Hero does say that a lot, but isn’t he still afraid of bugs?” Aubrey giggled, “Do you think he’ll ever be able to look at a bug without freezing up?”

“Maybe if there’s hundreds of us between the bug and him.” They both laughed and made up a variety of other situations where Hero had to face his fears. From bunny-spiders, which Aubrey insisted would be adorable, to Hero having to battle giant bugs in a giant robot. They went on to discuss their classmates, their friends, and what they thought would happen next on the next issue of Captain Spaceboy.

Eventually, the grandfather clock chimed, and their conversation slowly died down, and Aubrey, exhausted, stretched her arms and made a big yawn.

“Hey Sunny, can you keep the thing about my parents a secret?” She said in a small voice.

“Why?” Sunny didn’t understand, if they were going to help Aubrey, they’d have to tell the rest of their friends.

“I don’t really want anyone else to know about this. It’s kind of embarrassing. I mean, it’s not that bad since dad always manages to calm mom down.” Aubrey covered her face with the blanket, “I’m having so much fun with everyone right now and I don’t want a thing between any of us to change.”

“I do too, but I don’t think anything will change between us,” Sunny managed to stumble his words. His face flushed at what he was about to offer next, “if you ever want to talk, you can always come to me.”

“Thanks Sunny,” She let out a sigh of relief and then she yawned, “that’s really sweet.”

Aubrey felt a lot better. She remembered that she should go home soon, but the rug was soft, and the blanket was comfy. Her heart felt a lot lighter, the air felt a lot fresher, and she couldn’t muster the will to get up. It… should be fine to close her eyes a little, Sunny wouldn’t mind. She curdled the blanket a little closer to her, and relaxed.

Minutes passed as Aubrey slowly drifted deeper into her slumber, and Sunny tried to figure out what to do. He stared at Aubrey’s face for those many minutes to see if she was asleep, yes, she was indeed, definitely asleep. And he shouldn’t have moved or else he might wake her up, that’s why he had to stay in place, especially because he was next to her.

Suddenly, Sunny heard something outside the front door, without a moment’s hesitation, he immediately dove himself headfirst into the rug. If anyone saw him, either his parents or Mari, staring at Aubrey’s face, he’d literally explode. His thumping heart was beating hard against his chest. He kept his ears open, he held his breath, but eventually the sound stopped and nothing followed. Sunny waited a few seconds just to make sure the coast was clear.

Sunny peeked one eye open and looked out the front window. He found Mewo splashing outside in a large puddle in their garden. He let out a sigh of relief, it was just a false alarm. He didn’t know how Mewo got outside, but if she could get out, she could definitely find her way back in.

Sunny let himself relax, and plopped his head on the carpet, staring up to the ceiling. He thought about what just happened. And thus, the more rational part of his brain took over.

He brought his hands to his face. Did he really just say all that to Aubrey? It was incredibly cheesy. He couldn’t help but squirm, and then he thought of nudging a little closer to Aubrey and squirmed some more. He was definitely happy to get to know her a little better, but he really hoped that she didn’t notice his crush on her.

Aubrey shuffled a bit in her sleep due to Sunny’s wild dance on the floor, and Sunny froze still. He didn’t dare move another muscle, despite all his nervous energy.

Sunny needed to calm down, He remembered what Mari told him about how to do so. He needed to close his eyes, empty his mind, and focus on his breathing.

Sunny laid on the soft rug, as the pitter patter of the rain sounded in the distance, as the fire gave warmth and crackled away. The environment made it extremely easy for Sunny to relax.

Breathe in.

Breath out.

Within minutes, his breathing was completely steady, his mind completely empty, and his eyes completely shut. Indeed, Sunny was maintaining a perfect still state. Fifteen more minutes passed and he kept the same position perfectly. Indeed…

The rug had claimed another victim.

 

 

The sun was finally starting to peek out after the long rainy shower the town had all day. A beautiful orange glow was shining upon every surface as the sun began to set. The pools of water reflected this orange glow. It was akin to being in a room filled with giant Christmas lights. Mari was briskly walking down the street, bag in hand, looking immaculate as always.

She was finally done with every single class for the day. College prep classes were definitely no joke, a single class was more exhausting than a full day of school. The classwork was intense, but she found satisfaction in achieving excellence.

Though it did leave her quite hungry, she wanted to get some fruit to refresh herself as an afternoon snack. She’d make sure Sunny would have some too, she always had to urge him to eat healthily. He always ate what was in front of him with no regards for a balanced diet.

She fiddled with the keys in her hand as she reached the front door of her home. The entirety of the home was a plain mixture of beige and white, she wondered if Dad would ever consider painting the house a few more colors. Mari heard a small mew and looked at the garden, there she found Mewo sitting in the garden soaked from head to toe outside the door like an adorable furry garden gnome.

“Aw, Mewo, did you get locked outside?” She cooed, “Let’s get you inside and dry you off.” She picked up the kitten by the neck with an experienced touch and put her into her arms. She unlocked the door in one swift motion and slipped the keys back into her bag.

Mari stepped into the living room and dropped her bag in surprise (but not Mewo). The sight made her break into the most manic smile. She had to suppress a squeal so she wouldn’t wake what she was looking at.

Sunny and Aubrey, some of the two cutest kids she knew were both lazily napping in front of the fireplace. A number of towels littered the floor as well as a small pile of stuffed animals surrounded them and Aubrey was cuddling one as well. Mari quickly wished that Basil was here to take a photo of this moment, she wanted to get this picturesque scene in as many megapixels and angles as she can get.

But Mewo made another cry and Mari remembered she had to dry her kitten off. She had to reorganize her priorities, and well, the two weren’t going anywhere. She peeled off a towel from the towel onion and the hair drier (she would need to remember to clean up before mom got home) and walked up the stairs to the bathroom.

         Once she got Mewo’s fur all glossy and soft, Mari walked down the stairs back into the living room. She may not have a camera on her, nor in the house, but she’d engrave this moment into her mind. Unfortunately, the same moment she reached the bottom of the stairs, the front door opened again. Mari’s mother walked in and she was unaware of the sanctity of the moment and made a miraculous racket. Her keys clanked loudly against the bowl as they were tossed in, the door slammed shut harder than Mari had ever heard before, and her mother stomped her way through into her room. Mari recognized those signs, her mother must’ve had an awful workday today.

She sighed as one of the two sleeping angels were roused from their sleep as a hurricane known as their mother swept through their home. Sunny was able to sleep through the most incredible rackets. Well, if her other plans were ruined, she might as well speak to Aubrey to catch up.

Aubrey groggily got up. She rubbed her eyes whilst holding the bright yellow plushie. Yellow? Wasn’t Mr. Plantegg purple? She began to notice more and more discrepancies and she looked around, from how the soft rug definitely wasn’t her bed, to the unfamiliar blanket, to the older girl watching her with a bright giga-watt smile. Her eyes focused on the older girl’s face and she immediately panicked, it was Mari! Aubrey’s brain jolted awake and she threw the blanket to the side. Mari giggled at the scene and put out a hand for Aubrey to grab and pulled Aubrey up.

“Wakey wakey sleepyhead!” Mari lightly poked Aubrey on the forehead. Aubrey made a cute murgle in response. “Good afternoon Aubrey! Did you have a nice nap? And more importantly, why were you sleeping on the floor? It’s not very good for your back.” Mari asked with a smile.

“Well, uh,” Aubrey paused to think of a believable excuse, “a car splashed a bunch of water onto me while I was walking outside, so Sunny got me inside to dry off. And it was really warm! The fire was really cozy! And your rug is really soft and comfortable! So, um, I fell asleep...” Aubrey ran her toes on the carpet enjoying the feeling between her toes.

“And you just happened to fall asleep cuddling next to Sunny?” Mari’s smile grew until it was as wide as her face.

“N-no! It’s not like that! Um, I don’t know when Sunny fell asleep but… wait no! I wasn’t cuddling with him!” Aubrey blushed, “Was I…?”

“Nah Aubrey, I was just teasing.” Mari laughed.

“Daww, it’s getting late though, the sun has already set. Have you eaten anything?” Mari wondered. Aubrey shook her head in response.

  “Then, you should stay here for dinner Aubrey! There’s only another hour before dinner is ready.” Aubrey lit up for a moment, but Mari continued, “If you’re going to stay though, we’re going to have to call your parents though, they don’t know you’re here right?”

“Oh, thank you, but my dad made dinner tonight.” Aubrey lied. It was honestly a 50/50 chance that he did. Aubrey glanced at the clock, “It’s getting really late, so I have to be home soon. I think I’ll go right now.”

“Phooey, I’d offer to walk you home, but I think I need to bring Sunny up to bed.” The boy in particular slept silently, and somehow managed to wrap himself with the blanket that was tossed away earlier in his sleep.

“Bye Mari!” Aubrey said as she left through the front door, umbrella in hand. She reached the sidewalk and turned around, “See you tomorrow!” and began to run home.

As Aubrey bounced down the sidewalk, she chuckled to herself,

‘Today wasn’t such a bad day after all.’

**Comment by macimas** [comment]
# Omori (video game)
###### From Wikipedia, the free encyclopedia
Omori (stylized as OMORI) is a 2020 role-playing video game developed by indie studio Omocat.[a] Based on the director's Omori (ひきこもり, hikikomori) webcomic series, it was released in December 2020. Prominently featuring concepts such as anxiety and depression, the game has psychological horror elements. In the story, the player controls a hikikomori boy named Sunny and his dream world alter-ego Omori. They explore both the real world and the surreal dream world to overcome their fears and secrets. How they interact depends on choices made by the player, resulting in one of several endings. The game's turn-based battle system includes unconventional status effects based on the characters' emotions.

After a successful Kickstarter campaign, the game was delayed numerous times, and experienced several development difficulties. It was finally released for Microsoft Windows and macOS six years after its initial funding, and the developers also announced plans for a Japanese translation as well as ports to Nintendo Switch, PlayStation 4, and Xbox One. Omori was acclaimed by critics, who lauded it for its graphics, narrative elements, soundtrack, and depiction of anxiety and depression, favorably comparing it to EarthBound and Yume Nikki. The game went on to be nominated for several awards, winning DreamHack's "Daringly Dramatic" category in 2021.

| ![image](https://user-images.githubusercontent.com/42163944/128197548-87dd7437-bcbf-43e6-876b-9bb23c845df9.png) | Omori |
| --- | --- |
| Alt | *The cover art Omori is shown. On the top there is a logo that shows the text "OMORI" in a filtered hand-written text, with a black lightbulb making up the counter in the middle "O", on bottom a young person in a hand drawn art style is depicted.* |
Developer(s) | Omocat LLC
| Publisher(s) | Playism |
| Director(s) | Omocat
| Artist(s) | Omocat, Charlene Lu, Emily Shaw |
| Composer(s) | bo en, Jami LynnePedro Silva
| Engine | RPG Maker |
| Platform(s) | Microsoft Windows, macOS, Nintendo Switch, PlayStation 4, Xbox One |
| Release | (Microsoft Windows, macOS --- December 25, 2020) (PlayStation 4, Xbox One, Nintendo Switch --- TBA) |
| Genre(s) | Role-playing |
| Mode(s) | Single-player |



# Gameplay
| ![image](https://user-images.githubusercontent.com/42163944/128198331-1d94fbee-5510-4731-8ccb-26d870b8a574.png) | Omori utilizes a rock-paper-scissors type system during battles in which certain emotions are strong or weak against each other. |
| --- | :-- |

Omori's gameplay is inspired by traditional Japanese role-playing games.[1] The player controls a party of four characters: Omori, Aubrey, Kel, and Hero, each with their own skills in battle and the overworld.[2][1]

When exploring the overworld, the game is played from a top-down perspective.[3] It features side-quests and puzzles for the player to solve, which allow them to gain rewards and skills.[4][5][2] Weapons and items which benefit the party can be obtained throughout the game, including via purchasing them using the game's currency, Clams.[6][7][5] Outside of battle, the party can heal and save by encountering a picnic blanket, associated with Omori's older sister Mari.[7]

Battles are played out in a turn-based format, where each party member performs a move.[4] After attacking, party members can work together to perform "follow up" attacks.[7] Characters and enemies have heart,[6] which functions as health points; if damage is taken, it decreases, and if it reaches zero, the character is defeated and turns into toast.[5] The juice meter is used to perform skills, special abilities which aid in battle.[6]

Unlike most role-playing games, status effects are based on a three-pointed emotion system.[8] A party member or opponent's emotion can change throughout the course of a battle, usually due to moves by another party member or enemy.[5][2] Neutral is the baseline and has no effects, Angry increases attack but lowers defense, Sad increases defense but lowers speed, and Happy increases speed but lowers accuracy.[6] Emotions are either strong or weak against each other – Happy beats Angry, Angry beats Sad, and Sad beats Happy. Additionally, higher-intensity variants of each emotion also exist.[1]

# Plot
The titular main character, Omori, awakens in the "White Space", a small white room he has lived in "for as long as [he] can remember." He opens a door and enters the vibrant world of "Headspace", where he meets his older sister Mari, and his friends Aubrey, Kel, Hero, and Basil. They look through shared memories in Basil's photo album and decide to head to his house. Along the way, the album is damaged when Kel and Aubrey scuffle. Upon seeing an unfamiliar photo fall from it, Basil panics, and Omori is suddenly teleported back to White Space alone. He stabs himself with his knife, revealing the previous events to be the dreams of a teenage boy, Sunny.

Waking up in bed, Sunny discovers he is moving out in three days, and goes downstairs for a midnight snack. Confronted by a nightmarish hallucination, he dispels it by calming down, and returns to bed with his steak knife. Awakening once again in White Space, Omori reunites with Aubrey, Kel and Hero, and the four learn that Basil has gone missing. Deciding to rescue him, they travel to various parts of Headspace to search for him, with Mari helping along the way. The group gradually gets distracted by various situations they encounter, and their memories of Basil and their goal of rescuing him slowly disappear.

Meanwhile, in the waking world, Mari committed suicide four years ago, which led to the friend group diverging. Although Kel and Hero managed to recover somewhat emotionally, Sunny became a shut-in estranged from his old friends, Aubrey left after feeling betrayed by the group's apparent indifference to Mari's death, and Basil became neurotic and paranoid. Kel knocks on Sunny's door in an attempt to reconnect one last time. The player can either ignore Kel or answer the door; if they choose the former, Sunny stays inside for the remaining three days, doing chores and focusing on his dreams instead of reconciling.

If the latter option is chosen, Sunny and Kel discover Aubrey attacking Basil. They discover that she stole Basil's real-life photo album, ostensibly to stop him from vandalizing it. After fighting Aubrey again and retrieving the album, they return it to Basil with some photos missing, but he lets Sunny keep it. While eating dinner together, Basil is suddenly mortified to learn of Sunny's impending departure, revealing that he has similar hallucinations. In another fight the next day, Aubrey accidentally pushes Basil into a lake. Sunny tries to rescue him, and both are saved from drowning by the arrival of Hero. In the dream word, Omori and his friends return to Basil's now-dilapidated house, and he is transported to the more disturbing "Black Space". Basil appears many times within it, repeatedly attempting to talk to him about something before dying gruesomely. In the final room, Omori kills Basil, placing himself atop a throne of massive hands.

On the last day before Sunny's departure, the others reconcile with Aubrey and find the missing photos. Coming to terms with Mari's death, they decide to spend their final night together in Basil's house, even though he refuses to exit his room. That night, Sunny confronts the truth in his dreams: during an argument, he killed Mari by accidentally pushing her down the stairs. In denial that Sunny did it, Basil helped frame Mari's death as a suicide by hanging her corpse. Afterwards, they looked back and saw an open eye staring back at them, shaping their subsequent hallucinations. While Basil was consumed by guilt and self-loathing, Sunny's suicidal depression made him create Headspace and his dream persona Omori to mask his trauma. To hide the truth, Omori reset Headspace every time their memories escaped from Black Space. Sunny wakes up in the middle of the night; the player can either choose to enter Basil's room to confront him about Mari's death or head back to sleep.

# Endings
If the player answers Kel, then confronts Basil on the final day, Sunny and a mentally unstable Basil attack each other and eventually pass out. While unconscious, Sunny recalls his memories with Mari and his friends and faces Omori. Refusing to die, Omori defeats him and the player encounters the standard game over screen.

- If the player opts to try again, Sunny gets up and overcomes his guilt, eliminating Omori from his mind. In the real world, he wakes up in the hospital that he and Basil were sent to, and heads to the latter's bed. While surrounded by their friends, it is implied that Sunny tells them about Mari's death. Additionally, if the player watered Basil's garden daily in Headspace, an after-credits scene will show Basil waking up in the hospital. Him and Sunny smile at each other, and the hallucinations disappear from both boys, representing their newfound willingness to move on with their lives.

- Should the player choose not to continue, Sunny lets Omori overtake him. Waking up in the hospital, he commits suicide by jumping off the balcony.

Alternatively, if the player ignores Basil on the final day, Sunny and his friends will wake up to discover that Basil has committed suicide. Depending on the player's choice, Sunny can then either kill himself with his knife or move away with his guilt still unabated. If the player initially chooses to remain inside and avoid Kel, only a variant of this ending is available, with Sunny hearing an ambulance siren implying Basil's death.

# Development
Omori was developed over the course of six and a half years, directed by pseudonymous artist Omocat.[9][a] It is based on Omori (ひきこもり, hikikomori) , a webcomic Tumblr blog Omocat created to "help [her] cope with [her] problems during a confusing part of [her] life." Initially planned as a graphic novel, she switched its medium to a video game to enable the audience to make choices in the story. For the game engine, she chose RPG Maker, as she deemed it important to support an accessible platform and community.[10][11]

A Kickstarter campaign was launched in 2014, and was successfully funded within one day,[12][8] with an initial projected release date of May 2015. A Nintendo 3DS port was promised as a stretch goal, but ultimately never came to fruition due to the discontinuation of the console; backers were instead offered a Nintendo Switch port.[13] To aid the game's creation, Omocat hired several additional team members, including an RPG Maker expert, but still had a goal of keeping the team size small. Initially, she enlisted her musician friends Space Boyfriend and Slime Girls to help with the soundtrack; after being inspired by bo en's "My Time" and coming up with the idea of hidden music tracks, she contacted him as well.[10]

As development continued, the team had to change their version of the RPG Maker engine, using this opportunity to refine the game's visual style, story, and gameplay.[14] After crowdfunding money was exhausted, they relied on merchandise sales to continue development.[3] The game would be delayed into 2019 and early 2020, but would again miss both targets.[15][16]

Later in 2020, Omori received its final release date of December 25.[16] It was initially released on Microsoft Windows and macOS,[17] but the developers have promised ports for Nintendo Switch, PlayStation 4, and Xbox One.[16]

# Reception
Omori received generally favorable reviews, with the PC version earning an aggregated score of 87 out of 100 on Metacritic.[18] PC Gamer reviewer Rachel Watts praised both its combat and gameplay, saying the game had "all the makings of being a modern cult classic".[5] Patrick Hancock of Destructoid stated that he didn't "know the last game that really hit me so emotionally like [it] did", but criticised many gameplay elements, stating that they could ruin the experience for some players.[4]

Multiple publications positively reviewed the game's depiction of anxiety and depression, with Rock Paper Shotgun reviewer Kat Bailey comparing it to her real-life experiences.[1] According to her, the game managed to take overused themes regarding the subject and create a "memorable darkness". Watts stated that the game "captures this sentiment [of overcoming anxiety] masterfully", but criticised some parts of the game for being too dark.[5]

A majority of reviewers praised the game's writing and tone, comparing it to games such as EarthBound, Undertale, and Yume Nikki'.[1][5][7] Writing for Wired magazine, reviewer Julie Fukunaga commended the depth and psychological themes of the narrative, stating that "it is in this medium that Omori thrives".[7] Hancock praised the "juxtaposition" of serious and discomfiting themes with whimsical moments, stating he sometimes thought of the game's jokes "on a weekly basis".[4]

Reviewers' opinion of the game's combat varied. Hancock criticised the lack of strategical depth, stating that he "found a strategy that worked and basically just repeated it ad nauseam",[4] and claiming that the combat was "hardly necessary". Opposingly, Bailey praised the game's "well-executed" combat and "difficult" bosses, stating that they helped break up some of the dungeons.[1] In her review, Rachel Watts complimented the way the game's abilities made the party feel like a cohesive unit.[5]

The art direction also received positive reactions. Watts praised the art direction of the monsters, stating the mix of different art styles "really heightens the horror".[5] The "anime-style cut-ins" were praised by Bailey, who called them "surprisingly well-animated".[1] Despite his criticism of the game's battles, Hancock stated he often anticipated them due to the artstyle, calling it "nothing short of phenomenal".[4]

# Awards
Omori received two Honorable Mentions at the 2021 Independent Games Festival.[19] It was also nominated for three categories in DreamHack's 2021 "Dreamies" awards, winning the "Daringly Dramatic" prize.[20]
